---
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: volcano
  namespace: fleet-default
spec:
  rkeConfig:
    machineGlobalConfig:
      etcd-expose-metrics: false
      profile: null
    machineSelectorConfig:
      - config:
        protect-kernel-defaults: false
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        drainBeforeDelete: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: volcano-pool-cp
        name: pool-cp
        quantity: 3
        unhealthyNodeTimeout: 0s
      - workerRole: true
        drainBeforeDelete: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: volcano-pool-worker
        name: pool-worker
        quantity: 2
        unhealthyNodeTimeout: 0s
