---
kind: MachineInventorySelectorTemplate
apiVersion: elemental.cattle.io/v1beta1
metadata:
  name: volcano-pool-cp
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchLabels:
          cores: "4"
          element: fire
---
kind: MachineInventorySelectorTemplate
apiVersion: elemental.cattle.io/v1beta1
metadata:
  name: volcano-pool-worker
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchLabels:
          cores: "2"
          element: fire
