apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: elemental-registration
  namespace: fleet-local
spec:
  branch: main
  paths:
    - /manifests/registration/
  repo: https://github.com/davidcassany/elemental-resources
  targets:
    - clusterSelector:
        matchExpressions:
          - key: provider.cattle.io
            operator: NotIn
            values:
              - harvester
